const projectLoadingStatusEnum = {
  NOT_STARTED: 'NOT_STARTED',
  FETCHING_PROJECT: 'FETCHING_PROJECT',
  FETCHED_PROJECT: 'FETCHED_PROJECT',
  FETCHING_PROJECT_COMPONENTS: 'FETCHING_PROJECT_COMPONENTS',
  FETCHED_PROJECT_COMPONENTS: 'FETCHED_PROJECT_COMPONENTS',
  FINISHED: 'FINISHED',
  FAILED: 'FAILED',
}

export default projectLoadingStatusEnum;